= Pflichtenheft
Stroschneider, Gruber, Breinesberger, Aichinger und Horner
:toc: left
:sectnums:
:toclevels: 1
:table-caption:

== Beschreibung der Ausgangslage

Wir sind ein Team aus 5 Schuelern und besuchen die Hoehere Technische Bundeslehranstalt Leonding.

== Ist-Zustand

Es gibt derzeit keine Kalorienzaehler-App mit den Features, die sich die Leute wuenschen.

== Problemstellung

Die Leute neigen dazu, Ihre Kalorien nicht zu zaehlen und haben keinen Ueberblick ueber ihren Kalorienverbrauch und ihre Kalorienaufnahme.

== Aufgabenstellung

=== Funktionale Anforderungen
==== Use-case diagram
[plantuml,ucd,png]
----
include::plantuml/Usecasediagram.puml[]
----

Das Program soll das aktuelle und das Wunschgewicht abfragen.

Außerdem sollen eingegebene Kalorien gezaehlt und ausgewertet werden.

Der Benutzer bekommt Vorschlaege wie er am effizientesten Kalorien verbrennen kann.

Nach laengerer Nutzungszeit sollen Statistiken zur Verfuegung stehen.

=== Nicht-funktionale Anforderungen

* Sicherheitsanforderung
- Daten müssen vor Dritten geschützt werden


== Zielsetzung

Die Nutzung der App soll Spaß machen und mehr Menschen zu Sport und Fitness motivieren.

== Rahmenbedingungen

Programmiersprache: Java

== Datenmodell
[plantuml,cld,png]
----
include::plantuml/Klassendiagramm.puml[]
----

== Lieferumfang

Der Kunde bekommt eine funktionierende App.

== Administratives

----
Kontakt: f.stroschneider@students.htl-leonding.ac.at

Team: Stroschneider, Gruber, Breinesberger, Aichinger und Horner
----