CREATE TABLE USER (
  EMAIL VARCHAR(30) CONSTRAINT NOT NULL,
  USERNAME VARCHAR(20),
  PASSWORD VARCHAR(20),
  WEIGHT DOUBLE,
  HEIGHT DOUBLE,
  PRIMARY KEY (EMAIL)
);

CREATE TABLE GOAL (
  WEIGHT DOUBLE,
  DEADLINE DATE
);

CREATE TABLE WORKOUT (
  NAME VARCHAR(20),
  CALORIES_BURNED DOUBLE,
  DURATION TIME
);

CREATE TABLE FOOD (
  NAME VARCHAR(20),
  CALORIES DOUBLE,
  AMOUNT INTEGER
);