CREATE TABLE GOAL (
    ID INTEGER NOT NULL CONSTRAINT GOAL_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    WEIGHT DOUBLE,
    DEADLINE DATE
);

CREATE TABLE ATHLETE (
    ATHLETE_ID  INTEGER NOT NULL CONSTRAINT ATHLETE_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    EMAIL       VARCHAR(50),
    USERNAME    VARCHAR(20),
    PASSWORD    VARCHAR(20),
    WEIGHT      DOUBLE,
    HEIGHT      DOUBLE,
    GOAL_ID     INTEGER CONSTRAINT GOAL_FK REFERENCES GOAL(ID)
);

CREATE TABLE FOOD (
    FOOD_ID INTEGER NOT NULL CONSTRAINT FOOD_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(20),
    CALORIES DOUBLE,
    AMOUNT INTEGER
);

CREATE TABLE CONSUMPTION (
    ATHLETE_CON_ID INTEGER NOT NULL CONSTRAINT ATHLETE_FK REFERENCES ATHLETE(ATHLETE_ID),
    FOOD_CON_ID INTEGER NOT NULL CONSTRAINT FOOD_FK REFERENCES FOOD(FOOD_ID),
    CONSTRAINT ATHLETE_MEALS_PK PRIMARY KEY (ATHLETE_CON_ID, FOOD_CON_ID)
);