-- Ziele
INSERT INTO GOAL (WEIGHT, DEADLINE) VALUES (60.9, DATE(2023100));

INSERT INTO GOAL (WEIGHT, DEADLINE) VALUES (118.3, DATE(2023100));

-- Benutzer
INSERT INTO CUSTOMER (EMAIL, USERNAME, PASSWORD, WEIGHT, HEIGHT, GOAL_ID)
VALUES ('m.mustermann@students.htl-leonding.ac.at', 'Max', 'MAXL123', 63.5, 176.3, 1);

INSERT INTO CUSTOMER (EMAIL, USERNAME, PASSWORD, WEIGHT, HEIGHT, GOAL_ID)
VALUES ('m.musterfrau@students.htl-leonding.ac.at', 'Marie', 'M4r1!', 60.1, 169.7, NULL);

INSERT INTO CUSTOMER (EMAIL, USERNAME, PASSWORD, WEIGHT, HEIGHT, GOAL_ID)
VALUES ('t.testinger@students.htl-leonding.ac.at', 'theodore', 'th3od?0r!', 120.1, 193.0, 2);

-- Essenstypen

INSERT INTO FOOD (NAME, CALORIES) VALUES ('APPLE', 95.0);
INSERT INTO FOOD (NAME, CALORIES) VALUES ('RICE', 205.0);
INSERT INTO FOOD (NAME, CALORIES) VALUES ('HAM', 186.0);

-- Konsumationen

INSERT INTO CONSUMPTION (CUSTOMER_CON_ID, FOOD_CON_ID, AMOUNT) VALUES (1, 3, 2);
INSERT INTO CONSUMPTION (CUSTOMER_CON_ID, FOOD_CON_ID, AMOUNT) VALUES (1, 1, 1);

INSERT INTO CONSUMPTION (CUSTOMER_CON_ID, FOOD_CON_ID, AMOUNT) VALUES (2, 1, 2);

INSERT INTO CONSUMPTION (CUSTOMER_CON_ID, FOOD_CON_ID, AMOUNT) VALUES (3, 2, 4);