@startuml

top to bottom direction

class User {
    - email: String
    - username: String
    - password: Hash
    - weight: Double
    - height: Double
}

class Goal {
    - weight: Double
    - dead-line: Date
}

class Food {
    - name: String
    - calories: Double
}

class CalorieCounter {
    + addMeal(meal: List<Food>): void
    + workout(calories: Double): void
}

User "1" - "1" Goal : > tries
Goal "1" - "1" CalorieCounter : > has
CalorieCounter "1" - "*" Food : > uses

@enduml
