@startuml

top to bottom direction

class User {
    - email: String
    - username: String
    - password: Hash
    - weight: Double
    - height: Double
}

class Goal {
    - weight: Double
    - deadline: Date
}

class Workout {
    - name: String
    - calories-burned: Double
    - duration: Double
}

User "1" - "1" Goal : > tries
Workout "1" - "*" User : < does

@enduml
